Repository entando/entando-plugin-jacms, pull requests merged in 2020-12, with the labels that each got.

#65 ENG-1513 Nonce Injection (includes also ENG-1579)
  pom.xml
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java
Labels: approved, size/M

#66 ENG-1562 validating id filter
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java
Labels: approved, size/M

#70 PARENT_POM_UPDATE-2020-12-10_21-46-11
  pom.xml
Labels: approved, size/XS

#67 ENG-1638 reverting nonce injection tag
  pom.xml
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java
Labels: approved, size/M

#68 ENG-1631 Returning bad format instead of empty list in case of filter…
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResource.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResourceController.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/validator/ContentModelValidator.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java
Labels: approved, size/M

#69 ENG-1638 Velocity templates nonce injection
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/JacmsSystemConstants.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/widget/ContentViewerHelper.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/dispenser/ContentRenderizationInfo.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/renderer/ContentWrapper.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/security/VelocityNonceInjector.java
  src/main/resources/spring/plugins/jacms/aps/cms-contentmodel-dictionary-config.xml
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/widget/ContentViewerHelperIntegrationTest.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/dispenser/TestContentDispenser.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java
Labels: approved, size/L

#72 ENG-1605 Fixing monolist metadata
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_valid_with_monolist_2_images.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_with_monolist_2_images.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: approved, size/L

#73 ENG-1578 add validation for referenced resources in the delete assets API
  pom.xml
  src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/validator/ResourcesValidator.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: approved, size/L

#74 ENG-1630: adding date format to News Archive widget
  src/main/resources/sql/plugins/jacms/port_data_production.sql
Labels: size/XS
