Repository entando/entando-plugin-jacms, pull requests merged in 2020-10, with the labels that each got.

#39 Eng 1348 update core parent
  pom.xml
Labels: approved, size/XS

#36 ENG-1206: Introduced EMAIL attribute type
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/entryContent.jsp
Labels: approved, size/XS

#35 ENG-1244 widgetcatalog readonlyDefaultConfig field added
  pom.xml
  src/main/resources/sql/plugins/jacms/port_data_production.sql
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: approved, size/M

#40 ENG-1349 search form rename + convert to ootb widget spec
  src/main/resources/sql/plugins/jacms/port_data_production.sql
Labels: approved, size/S

#30 ENG-531: Core upgrade for redis integration
  pom.xml
  src/main/resources/spring/plugins/jacms/aps/managers/cmsManagersConfig.xml
  src/test/java/org/entando/entando/plugins/jacms/web/contenttype/ContentTypeResourceIntegrationTest.java
Labels: approved, size/S

#38 ENG-1180: Improve support for clustered environments
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModelManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/cache/ContentModelManagerCacheWrapper.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentpagemapper/ContentPageMapperManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentpagemapper/cache/ContentMapperCacheWrapper.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/cache/ResourceManagerCacheWrapper.java
Labels: approved, do-not-merge/work-in-progress, size/S

#42 ENG-1385: Restore test execution on jacms
  src/test/java/com/agiletec/plugins/jacms/AllTests.java
Labels: approved, size/L

#43 ENG-1276 CMS widget renaming
  src/main/resources/sql/plugins/jacms/port_data_production.sql
Labels: approved, size/XS

#41 ENG-1171: Fix random failures when saving contents
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/CmsHypertextAttribute.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/LinkAttribute.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/ApiContentInterface.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/command/InsertOnlineContentBulkCommand.java
  src/main/resources/spring/plugins/jacms/aps/managers/bulkCommandConfig.xml
  src/test/java/com/agiletec/plugins/jacms/AllTests.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/TestValidateContent.java
  src/test/java/com/agiletec/plugins/jacms/apsadmin/content/TestContentBulkAction.java
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: approved, size/L

#44 ENG-978 Be sure access to digital assets is allowed to roles validateContents, editContents and manageResources
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesServiceUnitTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: approved, size/M

#46 ENG-963 fixing clone asset
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractResource.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: approved, size/L

#47 ENG-978 changed permissions on getContentSettings API
  src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/ContentSettingsController.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentsettings/ContentSettingsControllerIntegrationTest.java
Labels: approved, size/S

#48 ENG-963 fixing clone asset for protected images
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractResource.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
Labels: approved, size/S

#50 ENG-963 Fixing svg asset upload
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ImageResource.java
Labels: approved, size/XS

#51 ENG-1244 refactor to readonly page widget config
  pom.xml
  src/main/resources/sql/plugins/jacms/port_data_production.sql
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: approved, size/S

#45 ENG-1395 Adds support for cms assets and contents correlation using code
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/IResourceDAO.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/IResourceManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceDAO.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractResource.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/BaseResourceDataBean.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceDataBean.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceDto.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceInterface.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceRecordVO.java
  src/main/java/com/agiletec/plugins/jacms/apsadmin/resource/ResourceAction.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/init/portdb/Resource.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/model/AssetDto.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/model/FileAssetDto.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/model/ImageAssetDto.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/request/CreateResourceRequest.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/validator/ResourcesValidator.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/mock/MockResourceDataBean.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_valid.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid.json
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: approved, size/L

#53 ENG-1363 Fixing headless exception for png file upload
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ImageResource.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/imageresizer/PNGImageResizer.java
  src/test/java/com/agiletec/plugins/jacms/AllTests.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/imageresizer/PNGImageResizerTest.java
  src/test/resources/images/entando.png
Labels: approved, size/L

#52 ENG-1392: Fix bug on content renderization (fixed template Id)
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/widget/ContentViewerHelper.java
  src/main/java/com/agiletec/plugins/jacms/aps/tags/ContentTag.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/Jdk11CompatibleDateFormatter.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/widget/ContentViewerHelperIntegrationTest.java
Labels: approved, size/L
