Repository entando/entando-plugin-jacms, pull requests merged in 2020-11, with the labels that each got.

#55 ENG-1276 Add widgetCategory field
  pom.xml
  src/main/resources/sql/plugins/jacms/port_data_production.sql
Labels: approved, size/S

#54 ENG-1437 Improve content edit button
  src/main/resources/sql/plugins/jacms/port_data_production.sql
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/content_viewer.jsp
Labels: approved, size/M

#57 ENG-1452 Updating bom version
  pom.xml
Labels: approved, size/XS

#58 ENG-1452 Updating bom version
  pom.xml
Labels: approved, size/XS

#59 ENG-1402 viewPage added to JAXBContentType and ApiContentTypeInterface
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/ApiContentTypeInterface.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/model/JAXBContentType.java
  src/test/java/com/agiletec/plugins/jacms/AllTests.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModelManagerIntegrationTest.java
  src/test/java/com/agiletec/plugins/jacms/apsadmin/content/model/TestContentModelFinderAction.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/api/TestApiContentTypeInterface.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: approved, size/L

#60 ENG-1506 amend content template edit link to point to AppBuilder inst…
  src/main/resources/sql/plugins/jacms/port_data_production.sql
Labels: approved, size/XS

#61 ENG-1512: Added extra param "csp.header.extraConfig"
  src/test/config/conf/systemParams.properties
Labels: approved, size/XS

#62 ENG-1520: Added new api for content type attributes
  pom.xml
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentTypeService.java
  src/main/java/org/entando/entando/plugins/jacms/web/content/ContentTypeResource.java
  src/main/java/org/entando/entando/plugins/jacms/web/content/ContentTypeResourceController.java
  src/test/java/org/entando/entando/plugins/jacms/web/contenttype/ContentTypeResourceIntegrationTest.java
Labels: approved, size/L

#63 ENG-1450 Stop duplicating images when default images are created
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/IResourceManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractMultiInstanceResource.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractResource.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AttachResource.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ImageResource.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/ResourceInterface.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/ApiResourceInterface.java
  src/test/java/com/agiletec/plugins/jacms/AllTests.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/model/AbstractMultiInstanceResourceTest.java
Labels: approved, size/L

#49 ENG-1410: Fix bug on sorting by attribute role
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/IIndexerDAO.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/IndexerDAO.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/NumericSearchEngineFilter.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/SearcherDAO.java
  src/test/java/com/agiletec/plugins/jacms/AllTests.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/AdvContentSearchTest.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/CustomConfigTestUtils.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/FacetSearchEngineManagerIntegrationTest.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/SearchEngineManagerIntegrationTest.java
  src/test/resources/spring/dateAttributeRoleManagerConfig.xml
  src/test/resources/spring/dateAttributeRoles.xml
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: approved, size/XXL

#64 ENG-1512: Update BOM and snapshot version
  pom.xml
Labels: approved, size/XS
