Repository entando/entando-plugin-jacms, pull requests merged in 2020-08, with the labels that each got.

#19 ENG-964: Fix wrong sql script
  src/main/resources/sql/plugins/jacms/port_data_production.sql
Labels: approved, size/S

#10 ENG-955 Changing assets API to take into account linkability
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/request/ListResourceRequest.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: size/L

#17 ENG-970 test fix
  pom.xml
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_groups.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: approved, size/L

#20 ENG-875: Renaming CMS widgets
  src/main/resources/sql/plugins/jacms/port_data_production.sql
Labels: approved, size/S

#21 ENG-997 integration tests
  pom.xml
  src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerIntegrationTest.java
Labels: approved, size/L

#22 ENG-812 Fix versioning menu permissions
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/template/subMenu.jsp
Labels: size/S

#23 Eng 950 import bom
  README.md
  jenkins-x.yml
  pom.xml
Labels: size/M

#25 ENG-986 Additional Fixes for Content Type Idempotency
  pom.xml
  src/test/java/com/agiletec/plugins/jacms/ControllersAllTests.java
  src/test/java/org/entando/entando/plugins/jacms/web/contenttype/1_type_valid.json
  src/test/java/org/entando/entando/plugins/jacms/web/contenttype/ContentTypeResourceControllerTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/contenttype/ContentTypeResourceIntegrationTest.java
Labels: size/L

#27 Revert changes for ENG-1074 erroneously merged to master
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModel.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/tags/ContentInfoTag.java
Labels: size/S
