Repository entando/entando-plugin-jacms, pull requests merged in 2020-07, with the labels that each got.

#2 Eng 827 finalizing pipelines
  README.md
  pom.xml
  src/main/java/org/entando/entando/plugins/jacms/aps/servlet/ProtectedResourceProvider.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelService.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelUsageDetailsRequestListProcessor.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelReferencesRequestListProcessor.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResource.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResourceController.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/model/ContentModelReferenceDTO.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/validator/ContentModelReferencesValidator.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/validator/ContentModelUsageDetailsValidator.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/ContentSettingsController.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/layouts/assets-more/content_contentFinding.jsp
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/contentFinding.jsp
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerUnitTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentsettings/ContentSettingsControllerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/page/PageConfigurationControllerWidgetsIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: size/XXL

#3 ENG-877: Add LICENSE file
  LICENSE
Labels: size/L

#4 ENG-715 Changing annotation for crop ratio
  src/main/java/org/entando/entando/plugins/jacms/web/contentsettings/model/ContentSettingsCropRatioRequest.java
Labels: size/XS

#5 ENG-875 Renaming cms widgets
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: size/S

#7 ENG-859 Fixing composite attribute to not rely on the json order
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_type_with_composite_image_text.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_valid_with_composite_image_text.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_with_composite_image_text.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: size/L

#8 ENG-415
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentTypeService.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/ContentTypeServiceTest.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentTypeResourceIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelControllerIntegrationTest.java
Labels: approved, size/L

#9 ENG-803 extending content api to consider linkability
  pom.xml
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/main/java/org/entando/entando/plugins/jacms/web/content/validator/RestContentListRequest.java
  src/test/config/conf/systemParams.properties
  src/test/java/org/entando/entando/plugins/jacms/apsadmin/content/ContentServiceTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: size/L

#11 ENG-950 remove admin-console war dependency
  pom.xml
Labels: approved, size/XS

#14 ENG-936 Amend CMS sub-menu
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/template/subMenu.jsp
Labels: approved, size/L

#6 Update README.md
  README.md
Labels: size/XS

#13 ENG-844 fix for rendering the ContentViewer widget using default content model
  src/main/java/com/agiletec/plugins/jacms/aps/tags/ContentTag.java
Labels: approved, size/XS

#12 ENG-964: Added default resources
  src/main/resources/sql/plugins/jacms/port_data_production.sql
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/content_viewer.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/content_viewer_list.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/pagerBlock.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-category.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-Boolean-ignoreOption.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-Boolean.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-CheckBox.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-Date.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-Enumerator.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-EnumeratorMap.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-Number.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-Text.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-entity-ThreeState.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module-fulltext.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/inc/userFilter-module.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/row_content_viewer_list.jsp
  src/main/webapp/WEB-INF/plugins/jacms/aps/jsp/widgets/search_result.jsp
Labels: approved, lgtm, size/XL

#16 Eng 950 removed admin console war
  OWNERS
  OWNERS_ALIASES
  pom.xml
Labels: size/M

#18 ENG-935: removing tertiary menu
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/common/template/subMenu.jsp
Labels: approved, size/L
