Repository entando/entando-plugin-jacms, pull requests merged in 2021-05, with the labels that each got.

#85 ENG-2369 Changing filter value object to a date. Postgresql doesnt ac…
  pom.xml
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
  src/main/java/org/entando/entando/plugins/jacms/web/resource/ResourcesController.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: approved, size/M

#86 ENG-2369 Attempt to fix JX pipeline
  jenkins-x.yml
Labels: approved, size/XS

#87 ENG-2238 adds link Additional Attributes
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/test/java/com/agiletec/plugins/jacms/apsadmin/content/ContentAdminActionIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_valid_with_some_links.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_with_link.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/web/contentsettings/ContentSettingsControllerIntegrationTest.java
Labels: approved, size/XXL

#84 ENG-2306: Added contents status API
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/IContentService.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/model/ContentsStatusDto.java
  src/main/java/org/entando/entando/plugins/jacms/web/content/ContentController.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: approved, size/XXL

#88 ENG-2313 Fixing cache configuration
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/IResourceDAO.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceDAO.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/resource/TestResourceDAO.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: approved, size/L

#89 ENG-2417: Performance improvement on APIs for assets
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/resource/ResourcesService.java
  src/test/java/org/entando/entando/plugins/jacms/web/resource/ResourcesControllerIntegrationTest.java
Labels: size/XL
