Repository entando/entando-plugin-jacms, pull requests merged in 2021-07, with the labels that each got.

#98 ENG-2178: Remove Data Types and Data Models
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/dictionary/ContentModelDictionary.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/dictionary/ContentModelDictionaryProvider.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/model/IEntityModelDictionary.java
  src/main/java/com/agiletec/plugins/jacms/apsadmin/content/model/ContentModelAction.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelService.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/ContentModelServiceImpl.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResource.java
  src/main/java/org/entando/entando/plugins/jacms/web/contentmodel/ContentModelResourceController.java
  src/main/resources/spring/plugins/jacms/aps/cms-contentmodel-dictionary-config.xml
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/dictionary/ContentModelDictionaryProviderIntegrationTest.java
  src/test/java/com/agiletec/plugins/jacms/apsadmin/category/TestTrashReferencedCategory.java
  src/test/java/com/agiletec/plugins/jacms/apsadmin/user/group/TestTrashReferencedGroup.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/contentmodel/ContentModelServiceImplTest.java
Labels: approved, size/L

#99 ENG-2400 Bumping version, updating entando-core-bom and entando-core-…
  pom.xml
Labels: approved, size/XS

#100 ENG-2178 Updating CMS versions to fix swagger docs
  pom.xml
Labels: approved, size/XS

#96 ENG-2342: Groups referenced by unpublished content should not be deleted
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentDAO.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: approved, size/M

#101 ENG-2342: Fix code smells
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentDAO.java
Labels: approved, size/S

#102 ENG-2172: Removed categories from entity objects
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/Content.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentDOM.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentHandler.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/IndexerDAO.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/model/JAXBContent.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/main/resources/spring/plugins/jacms/aps/cms-servicesConfig.xml
Labels: approved, size/L

#103 ENG-2471 NewGen workflow
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/Content.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentDOM.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentHandler.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/IndexerDAO.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/model/JAXBContent.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/main/resources/spring/plugins/jacms/aps/cms-servicesConfig.xml
Labels: prepared, size/XXL

#104 ENG-2471 NewGen workflow v1.0.1
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: prepared

#106 ENG-2172 fix remove category from entity
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/Content.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentDOM.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentHandler.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/IndexerDAO.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/model/JAXBContent.java
Labels: prepared

#107 ENG-2172 other fix remove category from entity
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/ContentDto.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentDOM.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/parse/ContentHandler.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/searchengine/SearchEngineManager.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/api/model/JAXBContent.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/main/resources/spring/plugins/jacms/aps/cms-servicesConfig.xml
  src/test/java/com/agiletec/plugins/jacms/apsadmin/content/ContentAdminActionIntegrationTest.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/api/TestApiContentInterface.java
Labels: prepared

#110 ENG-2554: Improvement of cms events
  pom.xml
  src/main/java/com/agiletec/plugins/jacms/aps/system/JacmsSystemConstants.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/event/PublicContentChangedEvent.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/ContentModelManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/contentmodel/event/ContentModelChangedEvent.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/ResourceManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/resource/event/ResourceChangedEvent.java
Labels: prepared

#112 ENG-2571: Improvement of crud methods signature
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/ContentManager.java
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/IContentManager.java
  src/test/java/com/agiletec/plugins/jacms/aps/system/services/content/TestContentManager.java
  src/test/java/com/agiletec/plugins/jacms/apsadmin/content/TestContentBulkAction.java
  src/test/java/org/entando/entando/plugins/jacms/aps/system/services/api/TestApiContentInterface.java
  src/test/resources/sql/plugins/jacms/port_data_test.sql
Labels: prepared
