Repository entando/entando-plugin-jacms, pull requests merged in 2021-04, with the labels that each got.

#79 #ENG-2145 Fixing null pointer with hyperlink with a resource
  src/main/java/com/agiletec/plugins/jacms/aps/system/services/content/model/attribute/CmsHypertextAttribute.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_type_with_hypertext_attribute.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_POST_valid_with_hypertext_attribute.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: approved, size/M

#80 ENG-2036: Fix security issues
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/hypertextAttribute/info-prev-value.jsp
  src/main/webapp/WEB-INF/plugins/jacms/apsadmin/jsp/content/modules/include/removeResourceSubmit.jsp
Labels: approved, size/L

#81 ENG-2183 Adding new request parameter to improve performance when onl…
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/ContentService.java
  src/main/java/org/entando/entando/plugins/jacms/aps/system/services/content/IContentService.java
  src/main/java/org/entando/entando/plugins/jacms/web/content/validator/RestContentListRequest.java
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: approved, size/L

#82 ENG-2259 Updating entando bom and parent version (ppom 6.3.9)
  pom.xml
Labels: approved, size/S

#83 ENG-2251 boolean attribute string tests
  pom.xml
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_with_boolean_false_string.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/1_PUT_valid_with_boolean_true_string.json
  src/test/java/org/entando/entando/plugins/jacms/web/content/ContentControllerIntegrationTest.java
Labels: approved, size/L
